### ISSUE TITLE
chrome下已因安全问题无法使用

### ISSUE THREAD

**Issue by cxgreat2014** [walkor/live-ascii-camera#1]
控制台:getUserMedia() no longer works on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.
camera.html:13 GET http://www.workerman.net/demos/live-ascii-camera/images/screenshot.png 404 (Not Found)

**Comment by cxgreat2014** [comment]
希望更新

**Comment by walkor** [comment]
已经更新到readme
